# =============================================================================
# KUBERNETES SECRETS AND CONFIGMAPS
# =============================================================================
# WARNING: These are example values. In production, use proper secret management
# like HashiCorp Vault, AWS Secrets Manager, or Azure Key Vault

apiVersion: v1
kind: Secret
metadata:
  name: saloon-secrets
  namespace: saloon-system
  labels:
    app: saloon-system
    component: secrets
type: Opaque
data:
  # JWT Secret - Generate with: openssl rand -base64 64
  jwt-secret: eW91cl9zdXBlcl9zZWN1cmVfand0X3NlY3JldF9oZXJlX21pbmltdW1fMjU2X2JpdHM=
  
  # Database Credentials
  db-root-password: cm9vdHBhc3N3b3Jk
  db-password: c2Fsb29uX3Bhc3N3b3Jk
  
  # Eureka Credentials
  eureka-password: cGFzc3dvcmQ=
  
  # Redis Password (if using authentication)
  redis-password: ""
  
  # Kafka Credentials (if using SASL/SSL)
  kafka-username: ""
  kafka-password: ""
  
  # External API Keys (if any)
  external-api-key: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: saloon-config
  namespace: saloon-system
  labels:
    app: saloon-system
    component: config
data:
  # =============================================================================
  # DATABASE CONFIGURATION
  # =============================================================================
  DB_NAME: "saloon_service"
  DB_USERNAME: "saloon_user"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  
  # Database Connection Pool Settings
  DATABASE_MAX_POOL_SIZE: "20"
  DATABASE_MIN_IDLE: "5"
  DATABASE_CONNECTION_TIMEOUT: "30000"
  DATABASE_IDLE_TIMEOUT: "600000"
  DATABASE_MAX_LIFETIME: "1800000"
  DATABASE_LEAK_DETECTION: "60000"
  
  # JPA/Hibernate Settings
  JPA_DDL_AUTO: "validate"
  JPA_SHOW_SQL: "false"
  JPA_FORMAT_SQL: "false"
  JPA_BATCH_SIZE: "30"
  
  # =============================================================================
  # EUREKA SERVICE DISCOVERY
  # =============================================================================
  EUREKA_USERNAME: "eureka"
  EUREKA_HOST: "discovery-server"
  EUREKA_PORT: "8761"
  
  # =============================================================================
  # REDIS CONFIGURATION
  # =============================================================================
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_TIMEOUT: "2000ms"
  REDIS_MAX_ACTIVE: "10"
  REDIS_MAX_IDLE: "10"
  REDIS_MIN_IDLE: "2"
  CACHE_TTL: "600000"
  
  # =============================================================================
  # KAFKA CONFIGURATION
  # =============================================================================
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_PRODUCER_ACKS: "all"
  KAFKA_PRODUCER_RETRIES: "3"
  KAFKA_PRODUCER_BATCH_SIZE: "16384"
  KAFKA_PRODUCER_BUFFER_MEMORY: "33554432"
  
  # =============================================================================
  # APPLICATION CONFIGURATION
  # =============================================================================
  SPRING_PROFILES_ACTIVE: "k8s"
  LOG_LEVEL_ROOT: "INFO"
  LOG_LEVEL_APP: "INFO"
  LOG_LEVEL_SQL: "WARN"
  LOG_LEVEL_SQL_BINDER: "WARN"
  LOG_LEVEL_GATEWAY: "INFO"
  LOG_LEVEL_ROUTES: "INFO"
  LOG_LEVEL_REDIS: "INFO"
  LOG_LEVEL_CACHE: "INFO"
  
  # =============================================================================
  # ACTUATOR & MONITORING
  # =============================================================================
  HEALTH_SHOW_DETAILS: "always"
  SWAGGER_ENABLED: "false"
  SWAGGER_UI_ENABLED: "false"
  
  # =============================================================================
  # CORS CONFIGURATION
  # =============================================================================
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Authorization,Content-Type,X-Requested-With"
  CORS_ALLOW_CREDENTIALS: "true"
  
  # =============================================================================
  # FEATURE FLAGS
  # =============================================================================
  AUDIT_LOGGING_ENABLED: "true"
  RATE_LIMITING_ENABLED: "true"
  CIRCUIT_BREAKER_ENABLED: "true"
  CACHE_ENABLED: "true"
  GATEWAY_MONITORING_ENABLED: "true"
  K8S_HEALTH_CHECKS: "true"
  METRICS_EXPORT_ENABLED: "true"
  DISTRIBUTED_TRACING_ENABLED: "true"
  
  # =============================================================================
  # MONITORING & TRACING
  # =============================================================================
  SLEUTH_ENABLED: "true"
  ZIPKIN_ENABLED: "true"
  ZIPKIN_URL: "http://zipkin-service:9411"
  TRACING_ENABLED: "true"
  TRACING_SAMPLING_PROBABILITY: "1.0"
  
  # =============================================================================
  # GATEWAY CONFIGURATION
  # =============================================================================
  GATEWAY_CONNECT_TIMEOUT: "5000"
  GATEWAY_RESPONSE_TIMEOUT: "30s"
  
  # =============================================================================
  # GRACEFUL SHUTDOWN
  # =============================================================================
  GRACEFUL_SHUTDOWN_TIMEOUT: "30s"
  
  # =============================================================================
  # KUBERNETES SPECIFIC
  # =============================================================================
  K8S_NAMESPACE: "saloon-system"
  K8S_ZONE: "default"
  K8S_CLUSTER: "default"
  K8S_DISCOVERY_ENABLED: "false"
  K8S_CONFIG_ENABLED: "false"
  K8S_SECRETS_ENABLED: "false"