name: CI/CD for API Gateway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Maven Settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn clean install -B -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/*.jar

  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t janindu3/api-gateway:${{ github.sha }} .
          docker tag janindu3/api-gateway:${{ github.sha }} janindu3/api-gateway:latest
          docker push janindu3/api-gateway:${{ github.sha }}
          docker push janindu3/api-gateway:latest